<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyVersion>10.2026.08.30</AssemblyVersion>

        <Title>Songhay S3 Shell</Title>
        <Description>The Studio AWS S3 Shell for commandline automation of Activities.</Description>
        <Authors>Bryan D. Wilhite</Authors>
        <Copyright>(c) 2026 Bryan D. Wilhite</Copyright>
        <Company>Songhay System</Company>

        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SonghayCore.S3\SonghayCore.S3.csproj" />
    </ItemGroup>

</Project>
