<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyVersion>10.0.2</AssemblyVersion>
        <RootNamespace>Songhay.S3</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <Title>Songhay AWS S3</Title>
        <Description>The Studio AWS S3 Activities.</Description>
        <Authors>Bryan D. Wilhite</Authors>
        <Copyright>(c) 2026 Bryan D. Wilhite</Copyright>
        <Company>Songhay System</Company>

    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0|AnyCPU'">
        <DocumentationFile>.\Songhay.S3.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OneOf" Version="3.0.271" />
        <PackageReference Include="SonghayCore" Version="10.0.2" />
        <PackageReference Include="AWSSDK.S3" Version="4.0.102.4" />
    </ItemGroup>

</Project>
