<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Songhay.S3</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0|AnyCPU'">
        <DocumentationFile>.\Songhay.S3.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="OneOf" Version="3.0.271" />
        <PackageReference Include="SonghayCore" Version="10.0.0" />
        <PackageReference Include="AWSSDK.S3" Version="4.0.102.4" />
    </ItemGroup>

</Project>
