### YamlMime:ManagedReference
items:
- uid: Songhay.Models.DeploymentEnvironment
  commentId: T:Songhay.Models.DeploymentEnvironment
  id: DeploymentEnvironment
  parent: Songhay.Models
  children:
  - Songhay.Models.DeploymentEnvironment.ConfigurationKey
  - Songhay.Models.DeploymentEnvironment.ConfigurationKeyDelimiter
  - Songhay.Models.DeploymentEnvironment.DefaultTraceSourceNameConfigurationKey
  - Songhay.Models.DeploymentEnvironment.DevelopmentEnvironmentName
  - Songhay.Models.DeploymentEnvironment.ProductionEnvironmentName
  - Songhay.Models.DeploymentEnvironment.StagingEnvironmentName
  langs:
  - csharp
  - vb
  name: DeploymentEnvironment
  nameWithType: DeploymentEnvironment
  fullName: Songhay.Models.DeploymentEnvironment
  type: Class
  source:
    remote:
      path: SonghayCore/Models/DeploymentEnvironment.cs
      branch: dev/version-8.0.0
      repo: git@github.com:BryanWilhite/SonghayCore.git
    id: DeploymentEnvironment
    path: SonghayCore/Models/DeploymentEnvironment.cs
    startLine: 5
  assemblies:
  - SonghayCore
  namespace: Songhay.Models
  summary: Defines the deployment environment.
  example: []
  syntax:
    content: public static class DeploymentEnvironment
    content.vb: Public Module DeploymentEnvironment
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Songhay.Models.DeploymentEnvironment.ConfigurationKey
  commentId: F:Songhay.Models.DeploymentEnvironment.ConfigurationKey
  id: ConfigurationKey
  parent: Songhay.Models.DeploymentEnvironment
  langs:
  - csharp
  - vb
  name: ConfigurationKey
  nameWithType: DeploymentEnvironment.ConfigurationKey
  fullName: Songhay.Models.DeploymentEnvironment.ConfigurationKey
  type: Field
  source:
    remote:
      path: SonghayCore/Models/DeploymentEnvironment.cs
      branch: dev/version-8.0.0
      repo: git@github.com:BryanWilhite/SonghayCore.git
    id: ConfigurationKey
    path: SonghayCore/Models/DeploymentEnvironment.cs
    startLine: 10
  assemblies:
  - SonghayCore
  namespace: Songhay.Models
  summary: The configuration key.
  example: []
  syntax:
    content: public const string ConfigurationKey = "environment"
    return:
      type: System.String
    content.vb: Public Const ConfigurationKey As String = "environment"
- uid: Songhay.Models.DeploymentEnvironment.ConfigurationKeyDelimiter
  commentId: F:Songhay.Models.DeploymentEnvironment.ConfigurationKeyDelimiter
  id: ConfigurationKeyDelimiter
  parent: Songhay.Models.DeploymentEnvironment
  langs:
  - csharp
  - vb
  name: ConfigurationKeyDelimiter
  nameWithType: DeploymentEnvironment.ConfigurationKeyDelimiter
  fullName: Songhay.Models.DeploymentEnvironment.ConfigurationKeyDelimiter
  type: Field
  source:
    remote:
      path: SonghayCore/Models/DeploymentEnvironment.cs
      branch: dev/version-8.0.0
      repo: git@github.com:BryanWilhite/SonghayCore.git
    id: ConfigurationKeyDelimiter
    path: SonghayCore/Models/DeploymentEnvironment.cs
    startLine: 15
  assemblies:
  - SonghayCore
  namespace: Songhay.Models
  summary: The configuration key delimiter.
  example: []
  syntax:
    content: public const string ConfigurationKeyDelimiter = "."
    return:
      type: System.String
    content.vb: Public Const ConfigurationKeyDelimiter As String = "."
- uid: Songhay.Models.DeploymentEnvironment.DefaultTraceSourceNameConfigurationKey
  commentId: F:Songhay.Models.DeploymentEnvironment.DefaultTraceSourceNameConfigurationKey
  id: DefaultTraceSourceNameConfigurationKey
  parent: Songhay.Models.DeploymentEnvironment
  langs:
  - csharp
  - vb
  name: DefaultTraceSourceNameConfigurationKey
  nameWithType: DeploymentEnvironment.DefaultTraceSourceNameConfigurationKey
  fullName: Songhay.Models.DeploymentEnvironment.DefaultTraceSourceNameConfigurationKey
  type: Field
  source:
    remote:
      path: SonghayCore/Models/DeploymentEnvironment.cs
      branch: dev/version-8.0.0
      repo: git@github.com:BryanWilhite/SonghayCore.git
    id: DefaultTraceSourceNameConfigurationKey
    path: SonghayCore/Models/DeploymentEnvironment.cs
    startLine: 20
  assemblies:
  - SonghayCore
  namespace: Songhay.Models
  summary: The default trace source name configuration key.
  example: []
  syntax:
    content: public const string DefaultTraceSourceNameConfigurationKey = "defaultTraceSourceName"
    return:
      type: System.String
    content.vb: Public Const DefaultTraceSourceNameConfigurationKey As String = "defaultTraceSourceName"
- uid: Songhay.Models.DeploymentEnvironment.DevelopmentEnvironmentName
  commentId: F:Songhay.Models.DeploymentEnvironment.DevelopmentEnvironmentName
  id: DevelopmentEnvironmentName
  parent: Songhay.Models.DeploymentEnvironment
  langs:
  - csharp
  - vb
  name: DevelopmentEnvironmentName
  nameWithType: DeploymentEnvironment.DevelopmentEnvironmentName
  fullName: Songhay.Models.DeploymentEnvironment.DevelopmentEnvironmentName
  type: Field
  source:
    remote:
      path: SonghayCore/Models/DeploymentEnvironment.cs
      branch: dev/version-8.0.0
      repo: git@github.com:BryanWilhite/SonghayCore.git
    id: DevelopmentEnvironmentName
    path: SonghayCore/Models/DeploymentEnvironment.cs
    startLine: 25
  assemblies:
  - SonghayCore
  namespace: Songhay.Models
  summary: The development environment name.
  example: []
  syntax:
    content: public const string DevelopmentEnvironmentName = "dev"
    return:
      type: System.String
    content.vb: Public Const DevelopmentEnvironmentName As String = "dev"
- uid: Songhay.Models.DeploymentEnvironment.StagingEnvironmentName
  commentId: F:Songhay.Models.DeploymentEnvironment.StagingEnvironmentName
  id: StagingEnvironmentName
  parent: Songhay.Models.DeploymentEnvironment
  langs:
  - csharp
  - vb
  name: StagingEnvironmentName
  nameWithType: DeploymentEnvironment.StagingEnvironmentName
  fullName: Songhay.Models.DeploymentEnvironment.StagingEnvironmentName
  type: Field
  source:
    remote:
      path: SonghayCore/Models/DeploymentEnvironment.cs
      branch: dev/version-8.0.0
      repo: git@github.com:BryanWilhite/SonghayCore.git
    id: StagingEnvironmentName
    path: SonghayCore/Models/DeploymentEnvironment.cs
    startLine: 30
  assemblies:
  - SonghayCore
  namespace: Songhay.Models
  summary: The staging environment name.
  example: []
  syntax:
    content: public const string StagingEnvironmentName = "qa"
    return:
      type: System.String
    content.vb: Public Const StagingEnvironmentName As String = "qa"
- uid: Songhay.Models.DeploymentEnvironment.ProductionEnvironmentName
  commentId: F:Songhay.Models.DeploymentEnvironment.ProductionEnvironmentName
  id: ProductionEnvironmentName
  parent: Songhay.Models.DeploymentEnvironment
  langs:
  - csharp
  - vb
  name: ProductionEnvironmentName
  nameWithType: DeploymentEnvironment.ProductionEnvironmentName
  fullName: Songhay.Models.DeploymentEnvironment.ProductionEnvironmentName
  type: Field
  source:
    remote:
      path: SonghayCore/Models/DeploymentEnvironment.cs
      branch: dev/version-8.0.0
      repo: git@github.com:BryanWilhite/SonghayCore.git
    id: ProductionEnvironmentName
    path: SonghayCore/Models/DeploymentEnvironment.cs
    startLine: 35
  assemblies:
  - SonghayCore
  namespace: Songhay.Models
  summary: The production environment name.
  example: []
  syntax:
    content: public const string ProductionEnvironmentName = "prod"
    return:
      type: System.String
    content.vb: Public Const ProductionEnvironmentName As String = "prod"
references:
- uid: Songhay.Models
  commentId: N:Songhay.Models
  href: Songhay.html
  name: Songhay.Models
  nameWithType: Songhay.Models
  fullName: Songhay.Models
  spec.csharp:
  - uid: Songhay
    name: Songhay
    href: Songhay.html
  - name: .
  - uid: Songhay.Models
    name: Models
    href: Songhay.Models.html
  spec.vb:
  - uid: Songhay
    name: Songhay
    href: Songhay.html
  - name: .
  - uid: Songhay.Models
    name: Models
    href: Songhay.Models.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
